### ISSUE TITLE
(Android working) But not working with IOS 14.*

### ISSUE THREAD

**Issue by tyhour** [ytdl-js/react-native-ytdl#73]
I have problem with IOS can't get data response with error below.
TypeError: undefined is not an object (evaluating 'videoDetails.thumbnail.thumbnails
I was console.log in package and I see info = {"player_response": undefined}
Thanks for help.

**Comment by TylerOlthuizen** [comment]
I'm getting the same error too

**Comment by TylerOlthuizen** [comment]
What things have you tried during debugging?

**Comment by ninacoder-info** [comment]
same problem it's been working before

**Comment by Darguima** [comment]
I'm having the same problem on Android
I was reading the code and found that the 3 functions that receive information from the YouTube video (`getWatchHTMLPage`,` getWatchJSONPage`, `getVideoInfoPage` - defined in lib /info.js) are not receiving the desired response..

* `getWatchHTMLPage` - I think it is usually the function that is used, because if it works out the others are not used. The function is requesting the HTML code for the YouTube page, but instead is receiving a cookie consent page from Google and is unable to extract the information from the video - but I still don't know how to fix it

* `getWatchJSONPage` - this function is returning `parsedBody.reload === 'now'` what is triggering `throw Error('Unable to retrieve video metadata in watch.json');`

* `getVideoInfoPage` - is requesting an url like `https://www.youtube.com/get_video_info?video_id=${...}&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FwycjnCCgUes&ps=default&gl=US&hl=en` - but it seems to be returning a 404 error 


At this time I believe that the best solution is bypass the cookie consent page, but is the first time that I read this code so I'm not sure how really it's work

**Comment by tyhour** [comment]
> I found a workaround. You need edit the package on `node_modules` so it is undo when you run `yarn` or `npm install`. I already created a PR to correct it, just need wait be approved.
> 
> Add `html5: 1` to the query object on `node_modules/react-native-ytdl/lib/info.js`, on function `getVideoInfoPage` (about line 329)
> 
> Some like this:
> 
> ```
> query: {
>   video_id: id,
>   eurl: VIDEO_EURL + id,
>   ps: 'default',
>   gl: 'US',
>   hl: options.lang || 'en',
>   html5: 1
> }
> ```
> 
> I found the solution there:
> [fent/node-ytdl-core#923 (comment)](https://github.com/fent/node-ytdl-core/issues/923#issuecomment-843365128)



> I found a workaround. You need edit the package on `node_modules` so it is undo when you run `yarn` or `npm install`. I already created a PR to correct it, just need wait be approved.
> 
> Add `html5: 1` to the query object on `node_modules/react-native-ytdl/lib/info.js`, on function `getVideoInfoPage` (about line 329)
> 
> Some like this:
> 
> ```
> query: {
>   video_id: id,
>   eurl: VIDEO_EURL + id,
>   ps: 'default',
>   gl: 'US',
>   hl: options.lang || 'en',
>   html5: 1
> }
> ```
> 
> I found the solution there:
> [fent/node-ytdl-core#923 (comment)](https://github.com/fent/node-ytdl-core/issues/923#issuecomment-843365128)

Now I used ytdl-core with rest api for my app right now. I thinks this package not update anymore. So issue has been fixed for me.
